### ISSUE TITLE
File upload and download saying "unable to load external"

### ISSUE THREAD

**Issue by blindphoneman** [lroathe/GBBS#2]
Hi:

When I try to start a file upload or download, I get prompted for the file name, but, when I press Enter to begin as instructed, I get an error "Unable to load external" and the BBS hangs up.

Upon closer examination of the disks, it appears that 2 files "X.DN" and "X.UP" are not being copied to the destination media at install time.  The files are on the "GBBS.SYSTEM" disk but do not get copied to the mass storage device.

When I placed them in my /G/GBBS.PRO/SYSTEM" folder, the upload went successfully.

I didn't locate it in the BBS to download, but, it did upload with XModem successfully once I put "X.DN" and "X.UP" in my destination hard-drive.

Maybe you can check to see if the installer fails to copy other files, but, these are the 2 I found pretty quickly.

Thanks!

**Comment by lroathe** [comment]
Thank you for letting us know about this issue. We will look into the installer issue ASAP.

-Lane

**Comment by paulhlee1967** [comment]
This has been corrected in the latest release.
