### ISSUE TITLE
Cannot Read Documentation Files

### ISSUE THREAD

**Issue by codelogikllc** [lroathe/GBBS#4]
I really need to get some documentation on the 2.2 release. I even follow book links and there is no way to get it.  The files in the repo are garbled.

How do I read them. I am having issues with the system and it is dead as Julius .  I preferably need a PDF.

**Comment by paulhlee1967** [comment]
This is a known issue. Keep in mind all of this source had mostly been lost over the years, and this is what we were able to recover. The DOCS files are here only to maintain a "complete" set of known files. Perhaps someday we will find a way to read them.

In the meantime, there is a book available at callapple.org for v2.2 as well as one for the new and improved 2.3 version of GBBS "Pro" that should have everything you'd need to get your board up and running.

**Comment by paulhlee1967** [comment]
This is a known issue. Keep in mind these source files had all but been lost over the years. What we have assembled here is everything that was found while undertaking this project of open sourcing the GBBS Pro system.

Those DOC files are here for the sake of completeness. Perhaps someday we will find a way to read them. In the meantime, callapple.org has available docs/manuals for both v2.2 and the newest v2.3 releases of GBBS Pro. Either of those books will get you what you need to get your BBS up and running.
